method:
  template_program_path: "task_examples/cvrp_construct/template_algo.txt"
  task_description_path: "task_examples/cvrp_construct/task_description.txt"
  language: "python"
  num_samplers: 32
  num_evaluators: 2
  idea_prompt: false
  examples_per_prompt: 2
  samples_per_prompt: 4
  max_samples: 10000
  llm_max_tokens: null
  llm_timeout_seconds: 120
  db_num_islands: 10
  db_max_island_capacity: null
  db_reset_period: 14400
  db_cluster_sampling_temperature_init: 0.1
  db_cluster_sampling_temperature_period: 30000
  db_save_frequency: 100
  keep_metadata_keys: ["sample_time", "eval_time", "execution_time", "error_msg", "prompt", "response_text"]
  debug_mode: false
  debug_mode_crash: false

llm:
  class_path: "algodisco.providers.llm.openai_api.OpenAIAPI"
  kwargs:
    base_url: "http://localhost:8000/v1"
#    model: "meta-llama/Llama-3.1-8B-Instruct"
#    api_key: "${OPENAI_API_KEY}"  # vLLM does not verify keys; set any non-empty value

evaluator:
  class_path: "task_examples/cvrp_construct/evaluator.py:CVRPConstructEvaluator"
  kwargs: {}

logger:
  class_path: "algodisco.providers.logger.swanlab_logger.BaseSwanLabLogger"
  kwargs:
    logdir: "results/cvrp/funsearch/run2"
    project: "cvrp"
    experiment_name: "funsearch_run2"
    group: "funsearch"
    swanlab_logdir: "results/cvrp/funsearch/run2/swanlab"
    api_key: "${SWANLAB_API_KEY}"
